### ISSUE TITLE
Sticky Notes PopUpMenu doesn't open

### ISSUE THREAD

**Issue by NikoKrause** [collinss/Cinnamon-Sticky-Notes#11]
Hey,

I'm using the version from GitHub on Cinnamon 3.2.

If I press with the mouse on the sticky-note icon in the panel it doesn't open.
I'll get the following warning, when I look into `cinnamon --replace` from terminal:
```
(cinnamon:9587): Clutter-CRITICAL **: clutter_actor_set_child_below_sibling: assertion 'child->priv->parent == self' failed
```

Also i noticed the following:
The symbolic links in the `3.2` folder are broken on my machine.
https://github.com/collinss/Cinnamon-Sticky-Notes/blob/master/3.2/icons
https://github.com/collinss/Cinnamon-Sticky-Notes/blob/master/3.2/stylesheet.css

It's because the destination says:
```
/home/stephen/.......
```

Try to create them locally starting in the 3.2 folder, i.e.:
```
ln -s ../icons
ln -s ../stylesheet.css
```

And `icon.png` has to be in the 3.2 folder as well. Else the icon isn't shown in the "Add applet to panel"-menu.

**Comment by collinss** [comment]
Yeah, I've been seeing this as well, but I haven't had a chance to play with it yet. I use a custom menu class iirc, and it probably needs to be updated to support the changes I made when I removed the boxpointer.
