### ISSUE TITLE
Workspace switching and Window switching lag when notes are open

### ISSUE THREAD

**Issue by uigoku** [collinss/Cinnamon-Sticky-Notes#13]
This doesn't happen when the notes are in hidden mode, but when notes are kept up, the window as well as workspace switching lags

**Comment by collinss** [comment]
Do you have the shadows enabled in the settings? For some reason, this causes the Cinnamon process to use a lot of extra cpu.

**Comment by uigoku** [comment]
Yes, the shadows were enabled, but after disabling shadows the lag reduces to a smaller extent but it still lags upon window or workspace switching.
