### ISSUE TITLE
Battery Icon showing on notes after update to latest version

### ISSUE THREAD

**Issue by ChooChooAl** [collinss/Cinnamon-Sticky-Notes#14]
I just May 10 2017 noticed in the applets menu that there were updates to a few applets, this being one.
I'm running Linux Mint Cinnamon 17.3  64bit.   No issues like this before.
Now two colors themes green and red show, oddly enough, a green or red battery icon.  Icons that are probably used for battery status?!
![2017-06-10_18-47-31](https://user-images.githubusercontent.com/26556059/27006867-6185cd06-4e0e-11e7-823c-cd8321f6cd0f.png)

**Comment by collinss** [comment]
This is one of the weirdest bugs I've ever seen. I have no idea where that is coming from. Does this persist after a restart? What desktop theme are you using? Also, what other 3rd party applets do you have installed?

**Comment by ChooChooAl** [comment]
This is an old issue and should be closed.  I'm unsure of the resolution (it's now Oct 2017), I think reloading both sticky notes applet and battery desklet (the two getting mixed) fixed the problem.    There was no issue with THIS applet.
