### ISSUE TITLE
Some problems...

### ISSUE THREAD

**Issue by lestcape** [collinss/Cinnamon-Sticky-Notes#2]
- On applet removed, remove also the sticky from desktop.
- Caps lock is not recognized. Only when pressed with shift brings upper case charatcers. See: https://github.com/lestcape/Sticky-Notes/commit/68aadedb0e4b2da9cd7646d6cb0929b3d42fd190

**Comment by lestcape** [comment]
I have some cinnamon crashes when i try to close the notes, this is for the spices version... Thats good that you are active again... I miss your comments, normally on opposition to my comments jeje... I'm who experimented some problem with my monitor now.

**Comment by collinss** [comment]
Should be fixed now.

**Comment by lestcape** [comment]
That's good, thanks. Have a good day.
