### ISSUE TITLE
[Feature request] Bullets / Numbering for notes

### ISSUE THREAD

**Issue by anandrkris** [collinss/Cinnamon-Sticky-Notes#3]
It would be good to have simple bullets / auto-numbering feature. My To- do-lists usually are just bullet points. :smile: . Thanks.

**Comment by hyOzd** [comment]
What about simple markdown support?

**Comment by collinss** [comment]
@hyOzd That's a good idea, though not as simple as it sounds. Cinnamon doesn't currently have any widgets that support it so I would have to implement it manually, which would actually be a lot of work. While I might do this at some point in the future, it probably wont be any time soon.

**Comment by collinss** [comment]
There is now a checklist note type. I doubt I'll ever add auto bullets/numbering as this would be rather redundant.
