### ISSUE TITLE
Popup menu item "Remove this note" isn't shown

### ISSUE THREAD

**Issue by yrtimiD** [collinss/Cinnamon-Sticky-Notes#5]
Cinnamon 2.2.16
Sticky Notes 1.2

When performing right click on note only 3 menu items are shown:
- Change Theme
- Copy
- Paste

As result - no way to delete note at all.

**Comment by yrtimiD** [comment]
I'm not familiar with cinnamon applets programming, but saw that in buildMenu() function two types of menu items are used:
PopupMenu.PopupMenuItem and Applet.MenuItem

All "invisible" items are of Applet.MenuItem type.
I replaced "Remove" menu item to be:
```javascript 
    let remove = new PopupMenu.PopupMenuItem("Remove this note");
    this.menu.addMenuItem(remove);
    remove.connect("activate", Lang.bind(this, function() {
        this.emit("destroy", this);
    }));
```
and this seems to work.

**Comment by MyTheValentinus** [comment]
Thank, add this after copy menu entry and work !

**Comment by collinss** [comment]
I believe this issue is now fixed.
